version: '3.7'
services:
  php:
    build: 
      context: .
    image: phpdocker
    container_name: php
    ports:
     - "9000:9000"
    volumes:
     - ".:/var/www/html"
    command: php -S 0.0.0.0:9000 -t public/
    links:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: